import Head from 'next/head';
import Link from "next/link";

const Layout = ({ children, title="Crypto Land" }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a className="coin_logo">Crypto <span>Land</span></a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  )
}

export default Layout
